[versions]

# platforms
paper = "1.16.1-R0.1-SNAPSHOT"
groovy = "3.0.16"

# all modules (compileOnly)
univocity = "2.8.3"
placeholderapi = "2.11.5"
netty = "4.1.79.Final"
jetbrains-annotations = "26.0.2"

# plugins
screaming-plugin-builder = "2.0.0"
buildconfig = "6.0.7"
lombok = "9.2.0"

[libraries]
groovy = { group = "org.codehaus.groovy", name = "groovy", version.ref = "groovy" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
netty = { group = "io.netty", name = "netty-all", version.ref = "netty" }
univocity = { group = "com.univocity", name = "univocity-parsers", version.ref = "univocity" }

# platforms
paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper" }

[plugins]
screaming-plugin-builder = { id = "org.screamingsandals.plugin-builder", version.ref = "screaming-plugin-builder" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }