[versions]
# slib
screaming-lib = "2.0.3-SNAPSHOT"

# platforms
paper = "1.16.5-R0.1-SNAPSHOT"
groovy = "3.0.16"

# all modules (compileOnly)
configurate = "4.1.2"
configurate-patched-gson = "4.1.2-sandals-patch"
jetbrains-annotations = "26.0.2"

# plugins
screaming-plugin-builder = "2.0.0"
buildconfig = "6.0.7"
lombok = "9.2.0"

[libraries]
groovy = { group = "org.codehaus.groovy", name = "groovy", version.ref = "groovy" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

# configurate
configurate-core = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
configurate-gson = { group = "org.spongepowered", name = "configurate-gson", version.ref = "configurate-patched-gson" }
configurate-hocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
configurate-xml = { group = "org.spongepowered", name = "configurate-xml", version.ref = "configurate" }

# slib
slib-core-common = { group = "org.screamingsandals.lib", name = "core-common", version.ref = "screaming-lib" }
slib-core-bukkit = { group = "org.screamingsandals.lib", name = "core-bukkit", version.ref = "screaming-lib" }
slib-placeholders-common = { group = "org.screamingsandals.lib", name = "placeholders-common", version.ref = "screaming-lib" }

# platforms
paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper" }

[plugins]
screaming-plugin-builder = { id = "org.screamingsandals.plugin-builder", version.ref = "screaming-plugin-builder" }
screaming-plugin-slib = { id = "org.screamingsandals.plugin-slib", version.ref = "screaming-plugin-builder" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
